name: build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0'

      - name: checkout
        uses: actions/checkout@v4

      - name: go mod tidy
        run: go mod tidy

      - name: build and test
        run: just build

      - name: Convert coverage format to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.out
          outfile: coverage.lcov
        if: "matrix.os == 'ubuntu-latest'"

      - name: coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
        if: "matrix.os == 'ubuntu-latest'"
